PLATFORM = mac
PLATFORM_LIB = mac
PLATFORM_EXT = dylib

SHARED = -dynamiclib

include Makefile.common

CFLAGS += -DOSX -mmacosx-version-min=10.12
LIBS += -framework OpenGL -framework VideoToolbox -framework CoreVideo -framework CoreMedia -framework Foundation -framework AudioToolbox
